src/apps/accounts/urls.py
from django.urls import path
from . import views
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'accounts'


urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.logout_view, name='logout'),
    path('profile/<slug:slug>/', views.user_profile, name='profile'),

    path('edit-profile/', views.user_edit_profile, name='edit-profile'),


]





#برای class base view

urlpatterns += [
    path('login/', Login.as_view(), name='login'),

    path('password_reset/', CustomPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', CustomPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', CustomPasswordResetCompleteView.as_view(), name='password_reset_complete'),

]

src/apps/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('', views.cart_view, name='cart_view'),
    path('add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),

    path('remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('remove/<int:product_id>/<int:attribute_id>/', views.remove_from_cart, name='remove_from_cart_with_attr'),
    path('clear/', views.clear_cart, name='clear_cart'),
    path('increase/<int:product_id>/', views.increase_cart_quantity, name='increase_quantity'),
    path('increase/<int:product_id>/<int:attribute_id>/', views.increase_cart_quantity,name='increase_quantity_with_attr'),
    path('decrease/<int:product_id>/', views.decrease_cart_quantity, name='decrease_quantity'),
    path('decrease/<int:product_id>/<int:attribute_id>/', views.decrease_cart_quantity,name='decrease_quantity_with_attr'),

    path('order', views.order_cart, name='order_cart'),

]

src/apps/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',views.home,name='home'),
    path('category/<int:id>/', views.category_detail, name='category_detail'),
    path('category/<int:id>/<slug:slug>/', views.category_detail, name='category_detail'),
    path('product-class/<int:id>/', views.product_class_detail, name='product_class_detail'),
    path('product-class/<int:id>/<slug:slug>/', views.product_class_detail, name='product_class_detail'),
    path('product-detail/<int:id>/<slug:slug>', views.product_detail, name='product_detail'),
    path('product-favourite/<int:product_id>/', views.product_favourite, name='product_favourite'),
    path('favourites/', views.product_favourite_list, name='product_favourite_list'),
    path('top-selling/', views.top_selling_products, name='top_selling'),
    path('most-viewed/', views.most_viewed_products, name='most_viewed'),
]

src/config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.home.urls'),name='home'),
    path('accounts/',include('apps.accounts.urls'),name='accounts'),
    path('cart/',include('apps.cart.urls'),name='cart'),
]



if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fa" dir="rtl">

<head>
  <meta charset="UTF-8">
  <title>{% block title %}عنوان پیش‌فرض{% endblock %}</title>
    {% block css %} {% endblock %}

    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">


  <!-- Bootstrap Icons -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css" rel="stylesheet">

  <style>
    body {
      font-family: IRANSans, sans-serif;
      background-color: #f8f9fa;
    }
  </style>
</head>
<body>
    {% include 'navbar.html' %}
    {% include 'messages.html' %}
    {% block body %}{% endblock %}

  <!-- Bootstrap Bundle JS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoU3u6EfcM9Z2zWDF10lBvYUqW8CkZBv6zA2e6FQ1HXpZfF" crossorigin="anonymous"></script>
</body>
</html>

src/apps/templates/messages.html
{% if messages %}
  <div class="messages-container">
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <!-- آیکون اختیاری بر اساس نوع پیام -->
        {% if message.tags == 'success' %}
          <i class="fas fa-check-circle"></i>
        {% elif message.tags == 'error' %}
          <i class="fas fa-exclamation-circle"></i>
        {% elif message.tags == 'warning' %}
          <i class="fas fa-exclamation-triangle"></i>
        {% elif message.tags == 'info' %}
          <i class="fas fa-info-circle"></i>
        {% endif %}

        <!-- متن پیام -->
        {{ message }}

        <!-- دکمه بستن -->
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

src/apps/templates/navbar.html
<nav class="navbar bg-light p-3 shadow-sm">
    <div class="container d-flex justify-content-between align-items-center">
        <a href="{% url 'home:home' %}" class="navbar-brand"><i class="bi bi-house" style="font-size: 1.5rem;"></i></a>
        <ul class="nav">
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                    <a class="nav-link" href="{% url 'home:product_favourite_list' %}">
                        <i class="bi bi-heart"></i> علاقه‌مندی‌ها
                    </a>
                {% else %}
                    <a class="nav-link" href="{% url 'accounts:login' %}?next={% url 'home:product_favourite_list' %}">
                        <i class="bi bi-heart"></i> علاقه‌مندی‌ها
                    </a>
                {% endif %}
            </li>
            <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_view' %}">
                        <i class="bi bi-cart"></i> سبد خرید
                    </a>

            </li>
             {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:profile' slug=navbar_profile.slug %}">
                        <i class="bi bi-box-arrow-right"></i> پروفایل
                    </a>
                </li>

            {% endif %}









            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">
                        <i class="bi bi-box-arrow-right"></i> خروج
                    </a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">
                        <i class="bi bi-box-arrow-in-left"></i> ورود
                    </a>
                </li>
            {% endif %}



        </ul>
    </div>
</nav>